.gitignore, README.md, package-lock.json, package.json, tests/example/index.html, tests/example/js/necessary.js, tests/example/js/statistics.js
Added an example page that uses the cookie-consent javascript.
=> Add an example site for testing

.gitignore, README.md, package-lock.json, package.json, tests/example/index.html, webpack.config.js
Using webpack will help us to keep code modular, and facilitate better
testing.
https://webpack.js.org/
Using babel will allow us to use modern javascript, but keep backwards compatibility with older browsers.
https://babeljs.io/
=> Initial webpack + babel setup

.babelrc, README.md, jest.config.js, package-lock.json, package.json, src/cookieconsent.js, src/cookies.js, src/cookies.test.js
1. Adds the Jest testing framework
2. Add two *very simple* tests
3. Get the tests to pass by refactoring the get/set cookie code into it's own module.
=> Unit testing

.babelrc, jest.config.js, package-lock.json, package.json, tests/integration-tests/index.test.js
* Use puppeteer instead of jsdom
* Modify babel config to enable async/await usage in puppeteer tests
=> Add jest-puppeteer integration tests

src/cookies.test.js
Added some tests for the getCookie function (failing).
=> Add unit tests for getting and setting cookies

.eslintrc.js, package-lock.json, package.json
=> Add eslint config

__mocks__/htmlMock.js, jest.config.js, package-lock.json, package.json, src/cookieconsent.test.js, src/cookies.test.js, src/modal.html, src/modal.js, webpack.config.js
We don't need to define our html inside javascript. We can get webpack to do that for us.
https://webpack.js.org/loaders/html-loader/
`import html from './path/to/file.html'` will load the html file into a js variable.
=> Html loader

README.md, src/cookieconsent.js, src/cookieconsent.test.js, src/cookies.js
API functions to look at and change preferences with tests + readme
=> Cookie toggle consent

src/cookieconsent.js, src/enable.js, src/enable.test.js, tests/example/index.html, tests/integration-tests/index.test.js, tests/integration-tests/modal.test.js, tests/integration-tests/util.js
- Fix linting issues
- Refactor some code
=> Add functions and tests to enable scripts and iframes

src/cookieconsent.js, src/cookies.js, src/modal.js
- linting fixes
- other code cleanup things
=> Code cleanup

README.md, src/cookieconsent.js, tests/example/no-banner.html, tests/integration-tests/modal.test.js
Do not show the banner if `data-nobanner` is set
=> No modal mode

src/cookieconsent.js
- On window.load, use the cookie settings to enable the relevant iframes and scripts
=> Enable cookie usage on load

src/cookies.js, src/cookies.test.js
I've re-written the getCookie function. Now passing unit tests
=> fix unit tests for cookie retrieval

src/cookieconsent.js
Refactoring to separate low-level cookie logic from high-level consent setting.
=> Refactor code to separate concerns

src/cookieconsent.js, src/modal.html, src/modal.js, src/style.css
Changes to cookie banner for more passive design which:
- changes full modal to more passive cookie banner
- changes to how consent works, you need to consent or look at settings for banner to disappear
- QOL changes to getCookie code
=> Ui updates

README.md, package.json
=> Production build

.babelrc, package-lock.json, package.json, src/cookieconsent.test.js, tests/example/index.html, tests/example/js/show-cookie-data.js, tests/example/no-banner.html
=> Unit tests

src/cookieconsent.test.js, src/cookies.test.js, src/enable.js, src/enable.test.js, tests/example/js/necessary.js, tests/example/js/statistics.js
linting fixes for eslint. After this we can add linting to the pipeline
=> added linting fixes for eslint

package-lock.json, package.json
Our first officially versioned minor release
=> Release version 0.1.0

package-lock.json, package.json
Bug fixes:
- Add explicit font sizes to override rem sizing
- IE11 fixes
=> Release version 0.1.1

src/enable.js, src/enable.test.js, tests/example/index.html, tests/integration-tests/index.test.js
=> Fix bug with enabling inline-javascript

package-lock.json, package.json
Bug fixes:
- Fix inline javascript bug
- Add tests
=> Release version 0.1.2

src/banner.js, src/main.js, tests/integration-tests/banner.test.js
changed consenting rules to not accept consent if settings link is clicked
=> cookie consented rules

src/_success-banner.scss, src/banner.html
=> Fix poor color contrast on success banner

package-lock.json, src/cookieconsent.js, src/cookieconsent.test.js, src/cookies.js, tests/example/index.html, tests/integration-tests/index.test.js, tests/integration-tests/versioning.test.js
Changed default cookie settings because of new ICO guidance, and bumped the cookie version
=> Cookie rule changes

README.md, src/cookieconsent.js, src/cookieconsent.test.js, src/settings.js, src/settings.test.js, tests/example/cookie-settings.html, tests/integration-tests/banner.test.js
Do not show banner if we are on the policy page by using the policy URL setting
=> Hide banner on policy page

package-lock.json, package.json
We can tag a new release after this is merged.
=> Bump version to 0.4.0

package-lock.json, package.json, src/_cookie-banner.scss, src/banner.html, src/banner.js, src/cookieconsent.js, src/cookieconsent.test.js, src/style.scss, tests/integration-tests/banner.test.js
Update with new wording
Implement new button for accepting analytics cookies
Update unit tests as banner now receives callbacks for accepting necessary or analytics cookies Update integration tests to check expected behaviour when accepting analytics cookies
Update scss to style new buttons
Remove some scss imports (9% reduction in prod main.js size but up for discussion)
Update azure pipeline to use Node 12.x
Add JSDoc dependency, npm script, comments and documentation
Add Husky dependency to run linting and testing on git push
=> Phase 2 updates

README.md, package-lock.json, package.json, src/_cookie-banner.scss, src/banner.html, src/banner.js, src/cookieconsent.js, src/cookieconsent.test.js, src/style.scss, webpack.config.js
Add requests to URLs monitored in Splunk
Use nhsuk-frontend 3.x
Fix styling issues caused by REMs, font inheritance and colour inheritance
=> Add splunk logging

azure-pipelines.yml
Set LOG_TO_SPLUNK=true in our azure pipeline build
=> Set splunk logging env variable

package.json, src/cookieconsent.js
Correct the package.json version number.
Increment Cookie_version number for displaying the cookie again with new changes.
=> Correct the version number

package.json, src/cookieconsent.js
Change the package.json version number 0.5.2
=> correct version number

LICENSE
Copy the license from https://github.com/nhsuk/nhsuk-frontend
=> Add a MIT license

src/banner.html
https://developers.google.com/search/reference/robots_meta_tag#data-nosnippet-attr
resolves #106
=> [refs #106] prevent cookie banner content from appearing in search

README.md
=> typo: s/data-no-banner/data-nobanner

.gitpod.Dockerfile, .husky/gitleaks/config/README-gitleaks.md, .husky/gitleaks/config/gitleaks.toml, .husky/pre-commit, package-lock.json, package.json
Add gitleaks as a pre commit to turn the EQF criteria for this green. https://nhsd-jira.digital.nhs.uk/browse/TM-2745
=> Add gitleaks pre commit

.scannerwork/report-task.txt, azure-pipelines.yml
- Migrating away from SonarQube to NHS Digital SonarCloud ☁️
=> Migrate from SonarQube to SonarCloud

.gitignore, azure-pipelines.yml
- Add SonarCloud exclusions files generated by Jest tests coverage
=> SonarCloud file exclusions

tests/example/cookie-settings.html, tests/example/custom-link.html, tests/example/index.html, tests/example/no-banner.html
Add DOCTYPE and LANG to html examples pages
=> Add DOCTYPE and LANG to html examples pages

src/cookieconsent.js
Remove argument from function expecting none
=> Remove argument from function expecting none

src/cookieconsent.js, src/cookies.js, src/enable.js, src/style.css, tests/example/cookie-settings.html, tests/example/custom-link.html, tests/example/index.html
Tickets:
- TM-3082: https://nhsd-jira.digital.nhs.uk/browse/TM-3082
- TM-3079: https://nhsd-jira.digital.nhs.uk/browse/TM-3079
- TM-3081: https://nhsd-jira.digital.nhs.uk/browse/TM-3081
- TM-3078: https://nhsd-jira.digital.nhs.uk/browse/TM-3078
- TM-3080: https://nhsd-jira.digital.nhs.uk/browse/TM-3080
- TM-3083: https://nhsd-jira.digital.nhs.uk/browse/TM-3083
=> Code Smells 

src/cookieconsent.js
- Update COOKIE_VERSION number to 6
=> Update COOKIE_VERSION number

.gitignore, .husky/pre-commit, .vscode/settings.json, jest.config.js, lint-staged.config.js, package-lock.json, src/banner.test.js, src/cookieconsent.js, src/cookieconsent.test.js, src/main.js, tests/integration/.pylintrc, tests/integration/features/broadcast_share_consent.feature, tests/integration/features/consume_share_consent.feature, tests/integration/features/cookie_consent.feature, tests/integration/helpers/cookie_helper.py, tests/integration/helpers/page_config_helper.py, tests/integration/steps/cookie_steps.py, tests/integration/steps/navigation_steps.py
implement consumption of shared cookie consent
=> PROD-963: implement consumption of shared cookie consent

azure-pipelines.yml, src/analyticsCookieMatcher.js, src/analyticsCookieMatcher.test.js, src/cookieconsent.js, src/cookieconsent.test.js, src/cookies.js, src/cookies.test.js, tests/example/custom-link.html, tests/example/js/load-analytics-cookies.js, tests/example/js/show-cookie-data.js, tests/integration/config/local.ini, tests/integration/data/cookies/analytics-cookies.json, tests/integration/environment.py, tests/integration/features/consume_share_consent.feature, tests/integration/helpers/cookie_helper.py, tests/integration/helpers/navigation_helper.py, tests/integration/steps/cookie_steps.py, tests/integration/steps/navigation_steps.py, tests/integration/steps/shared_steps.py, tests/scripts/run-integration-tests.sh
Clean up state analytics cookies
=> PROD-1656: clean up state analytics cookies
